In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd
# pandas.read_excel() ----> pd.read_excel()

## Reading an excel file

In [3]:
df = pd.read_excel("movies_data.xlsx")

/Users/amitverma/Documents/GUVI/B-202/pandas/env/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [4]:
df.head()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,22,9.0,481,691,1,10718,88,69.0,8.0,I do not have enough information to answer. Pl...
1,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,3000000.0,...,2,0.0,4,0,1,5,1,1.0,4.8,NaN
2,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,NaN,...,12,6.0,108,226,0,4849,45,48.0,8.3,NaN
3,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,26435.0,...,23,18.0,203,12000,1,111841,413,260.0,8.3,NaN
4,Pandora's Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,9950.0,...,20,3.0,455,926,1,7431,84,71.0,8.0,NaN

In [5]:
df.tail()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
1333,Twin Falls Idaho,1999,Drama,English,USA,R,111,1.85,500000.0,985341.0,...,505,482.0,3166,180,0,3479,87,54.0,7.3,NaN
1334,Universal Soldier: The Return,1999,Action|Sci-Fi,English,USA,R,83,1.85,24000000.0,10431220.0,...,577,485.0,4024,401,0,24216,162,75.0,4.1,NaN
1335,Varsity Blues,1999,Comedy|Drama|Romance|Sport,English,USA,R,106,1.85,16000000.0,52885587.0,...,255,35.0,23369,0,0,35312,267,67.0,6.4,NaN
1336,Wild Wild West,1999,Action|Comedy|Sci-Fi|Western,English,USA,PG-13,106,1.85,170000000.0,113745408.0,...,4000,582.0,15870,0,2,129601,648,85.0,4.8,NaN
1337,Wing Commander,1999,Action|Adventure|Sci-Fi,English,USA,PG-13,100,2.35,30000000.0,11576087.0,...,586,362.0,2497,858,3,14747,338,85.0,4.1,NaN

In [6]:
df.shape

(1338, 26)

In [7]:
students = {'Name': ['Amit', 'Anitha', 'Aswini', 'RK'],
            'Gender': ['M', 'F', 'F', 'M'],
            'Age': [34, 24, 23, 26]}

student_df = pd.DataFrame(students)

In [9]:
# add a new column called 'Domain' the values should be NLP, CV, ML, Data Science
student_df['Domain'] = ['NLP', 'CV', 'ML', 'Data Science']

In [12]:
student_df.head()

     Name Gender  Age        Domain
0    Amit      M   34           NLP
1  Anitha      F   24            DL
2  Aswini      F   23            ML
3      RK      M   26  Data Science

In [11]:
student_df['Domain'][1] = 'DL'

/var/folders/rr/0n4wysh90tn8pghdwg390f580000gn/T/ipykernel_87341/2551000944.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  student_df['Domain'][1] = 'DL'
/var/folders/rr/0n4wysh90tn8pghdwg390f580000gn/T/ipykernel_87341/2551000944.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student_df['Domain'][1] = 'DL'

### Subsetting the columns

In [13]:
title_df = df['Title']
title_df.head()

0    Intolerance: Love's Struggle Throughout the Ages
1                      Over the Hill to the Poorhouse
2                                      The Big Parade
3                                          Metropolis
4                                       Pandora's Box
Name: Title, dtype: object

In [14]:
title_df = df.Title
title_df.head()

0    Intolerance: Love's Struggle Throughout the Ages
1                      Over the Hill to the Poorhouse
2                                      The Big Parade
3                                          Metropolis
4                                       Pandora's Box
Name: Title, dtype: object

In [15]:
# To access multiple columns, pass the name of columns as a list
column_df = df[['Title', 'Year', 'Language', 'IMDB Score']]
column_df.head()

,Title,Year,Language,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916,NaN,8.0
1,Over the Hill to the Poorhouse,1920,NaN,4.8
2,The Big Parade,1925,NaN,8.3
3,Metropolis,1927,German,8.3
4,Pandora's Box,1929,German,8.0

In [16]:
column_df.shape

(1338, 4)

### Rows subsetting

In [17]:
# loc function
df.loc[0]

Title                          Intolerance: Love's Struggle Throughout the Ages
Year                                                                        1916
Genres                                                         Drama|History|War
Language                                                                     NaN
Country                                                                      USA
Content Rating                                                         Not Rated
Duration                                                                     123
Aspect Ratio                                                                1.33
Budget                                                                  385907.0
Gross Earnings                                                               NaN
Director                                                           D.W. Griffith
Actor 1                                                             Lillian Gish
Actor 2                                                                Mae Marsh
Actor 3                                                              Walter Long
Facebook Likes - Director                                                    204
Facebook Likes - Actor 1                                                     436
Facebook Likes - Actor 2                                                      22
Facebook Likes - Actor 3                                                     9.0
Facebook Likes - cast Total                                                  481
Facebook likes - Movie                                                       691
Facenumber in posters                                                          1
User Votes                                                                 10718
Reviews by Users                                                              88
Reviews by Crtiics                                                          69.0
IMDB Score                                                                   8.0
Unnamed: 25                    I do not have enough information to answer. Pl...
Name: 0, dtype: object

In [18]:
df.loc[7]

Title                          A Farewell to Arms
Year                                          1932
Genres                           Drama|Romance|War
Language                                   English
Country                                        USA
Content Rating                             Unrated
Duration                                        79
Aspect Ratio                                  1.37
Budget                                    800000.0
Gross Earnings                                 NaN
Director                             Frank Borzage
Actor 1                                Gary Cooper
Actor 2                                Helen Hayes
Actor 3                             Adolphe Menjou
Facebook Likes - Director                       57
Facebook Likes - Actor 1                       998
Facebook Likes - Actor 2                       164
Facebook Likes - Actor 3                      99.0
Facebook Likes - cast Total                   1284
Facebook likes - Movie                         213
Facenumber in posters                            1
User Votes                                    3519
Reviews by Users                                46
Reviews by Crtiics                            42.0
IMDB Score                                     6.6
Unnamed: 25                                    NaN
Name: 7, dtype: object

In [19]:
df.loc[-1]

KeyError: -1

In [20]:
df.shape[0]

1338

In [21]:
df.loc[df.shape[0]-1]

Title                                  Wing Commander
Year                                              1999
Genres                         Action|Adventure|Sci-Fi
Language                                       English
Country                                            USA
Content Rating                                   PG-13
Duration                                           100
Aspect Ratio                                      2.35
Budget                                      30000000.0
Gross Earnings                              11576087.0
Director                                 Chris Roberts
Actor 1                                Saffron Burrows
Actor 2                                   David Suchet
Actor 3                                Jürgen Prochnow
Facebook Likes - Director                           38
Facebook Likes - Actor 1                           811
Facebook Likes - Actor 2                           586
Facebook Likes - Actor 3                         362.0
Facebook Likes - cast Total                       2497
Facebook likes - Movie                             858
Facenumber in posters                                3
User Votes                                       14747
Reviews by Users                                   338
Reviews by Crtiics                                85.0
IMDB Score                                         4.1
Unnamed: 25                                        NaN
Name: 1337, dtype: object

In [24]:
# I want to access the 0th, 99th, and the last row using loc
df.loc[[0, 99, df.shape[0]-1]]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,22,9.0,481,691,1,10718,88,69.0,8.0,I do not have enough information to answer. Pl...
99,A Hard Day's Night,1964,Comedy|Musical,English,UK,Approved,87,1.75,560000.0,515005.0,...,725,704.0,2538,0,1,31429,219,105.0,7.7,NaN
1337,Wing Commander,1999,Action|Adventure|Sci-Fi,English,USA,PG-13,100,2.35,30000000.0,11576087.0,...,586,362.0,2497,858,3,14747,338,85.0,4.1,NaN

In [25]:
# iloc function
df.iloc[[0, 99, -1]]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,22,9.0,481,691,1,10718,88,69.0,8.0,I do not have enough information to answer. Pl...
99,A Hard Day's Night,1964,Comedy|Musical,English,UK,Approved,87,1.75,560000.0,515005.0,...,725,704.0,2538,0,1,31429,219,105.0,7.7,NaN
1337,Wing Commander,1999,Action|Adventure|Sci-Fi,English,USA,PG-13,100,2.35,30000000.0,11576087.0,...,586,362.0,2497,858,3,14747,338,85.0,4.1,NaN

## Subsetting Rows and Columns
--------------------------------
> ### Syntax: Separate the rows and columns with comma
> ### the left part is the the rows, righ part is the columns
> ### we will be using the iloc function to merge the subsetting

In [26]:
df.head()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,22,9.0,481,691,1,10718,88,69.0,8.0,I do not have enough information to answer. Pl...
1,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,3000000.0,...,2,0.0,4,0,1,5,1,1.0,4.8,NaN
2,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,NaN,...,12,6.0,108,226,0,4849,45,48.0,8.3,NaN
3,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,26435.0,...,23,18.0,203,12000,1,111841,413,260.0,8.3,NaN
4,Pandora's Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,9950.0,...,20,3.0,455,926,1,7431,84,71.0,8.0,NaN

In [ ]:
'''
SELECT avg(IMDB_score), Year
FROM Movies
GROUP BY Year;
'''

In [27]:
df.iloc[3, 1]

np.int64(1927)

In [28]:
df.iloc[1:5, 1]

1    1920
2    1925
3    1927
4    1929
Name: Year, dtype: int64

In [29]:
df.iloc[[2, 4, 6, 9], [0, 5]]

                 Title Content Rating
2      The Big Parade       Not Rated
4       Pandora's Box       Not Rated
6       Hell's Angels          Passed
9  She Done Him Wrong        Approved

## Grouping and Aggregating in Pandas
--------------------------------------
>> #### a) For each year in our data, what was the average IMDB score? What about the average duration?

In [30]:
group_df = df.groupby('Year')['IMDB Score'].mean()
group_df.head(20)

Year
1916    8.000000
1920    4.800000
1925    8.300000
1927    8.300000
1929    7.150000
1930    7.800000
1932    6.600000
1933    7.100000
1934    8.200000
1935    7.800000
1936    7.850000
1937    7.750000
1938    7.500000
1939    8.166667
1940    7.420000
1941    7.800000
1942    8.000000
1943    7.000000
1944    6.500000
1945    7.550000
Name: IMDB Score, dtype: float64

In [31]:
df.groupby('Year')['Duration'].mean()

Year
1916    123.000000
1920    110.000000
1925    151.000000
1927    145.000000
1929    105.000000
           ...
1995    114.528571
1996    110.010101
1997    110.254237
1998    109.462687
1999    108.642857
Name: Duration, Length: 74, dtype: float64

In [32]:
df.groupby('Country')['IMDB Score'].mean()

Country
Aruba             4.800000
Australia         6.455556
Brazil            7.200000
Canada            6.336000
China             7.800000
Czech Republic    7.100000
Denmark           7.533333
France            6.761538
Germany           6.933333
Hong Kong         6.833333
India             7.800000
Iran              7.500000
Italy             7.418182
Japan             7.088889
Libya             8.400000
Mexico            6.800000
Netherlands       6.600000
New Zealand       7.500000
Norway            6.700000
Peru              5.400000
South Korea       2.700000
Soviet Union      8.100000
Spain             6.575000
Sweden            8.200000
Switzerland       5.800000
UK                6.873846
USA               6.672787
West Germany      7.266667
Name: IMDB Score, dtype: float64

In [33]:
df.groupby(['Country', 'Year'])['IMDB Score'].mean()

Country       Year
Aruba         1998    4.800000
Australia     1979    7.000000
              1981    7.600000
              1982    7.300000
              1985    6.200000
                        ...
USA           1998    6.418000
              1999    6.326515
West Germany  1967    6.000000
              1981    8.400000
              1984    7.400000
Name: IMDB Score, Length: 198, dtype: float64

In [34]:
df.groupby(['Country', 'Year'])[['IMDB Score', 'Duration']].mean()

                   IMDB Score    Duration
Country      Year
Aruba        1998    4.800000   91.000000
Australia    1979    7.000000   93.000000
             1981    7.600000   87.000000
             1982    7.300000  102.000000
             1985    6.200000  107.000000
...                       ...         ...
USA          1998    6.418000  110.420000
             1999    6.326515  107.924242
West Germany 1967    6.000000   80.000000
             1981    8.400000  293.000000
             1984    7.400000   94.000000

[198 rows x 2 columns]

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Title                        1338 non-null   object
 1   Year                         1338 non-null   int64
 2   Genres                       1337 non-null   object
 3   Language                     1333 non-null   object
 4   Country                      1338 non-null   object
 5   Content Rating               1316 non-null   object
 6   Duration                     1338 non-null   int64
 7   Aspect Ratio                 1308 non-null   float64
 8   Budget                       1281 non-null   float64
 9   Gross Earnings               1086 non-null   float64
 10  Director                     1338 non-null   object
 11  Actor 1                      1338 non-null   object
 12  Actor 2                      1338 non-null   object
 13  Actor 3                      1336 non-null   object
 14  Facebook Likes - Director    1338 non-null   int64
 15  Facebook Likes - Actor 1     1338 non-null   int64
 16  Facebook Likes - Actor 2     1338 non-null   int64
 17  Facebook Likes - Actor 3     1336 non-null   float64
 18  Facebook Likes - cast Total  1338 non-null   int64
 19  Facebook likes - Movie       1338 non-null   int64
 20  Facenumber in posters        1338 non-null   int64
 21  User Votes                   1338 non-null   int64
 22  Reviews by Users             1338 non-null   int64
 23  Reviews by Crtiics           1335 non-null   float64
 24  IMDB Score                   1338 non-null   float64
 25  Unnamed: 25                  1 non-null      object
dtypes: float64(6), int64(10), object(10)
memory usage: 271.9+ KB

In [36]:
df.head()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,22,9.0,481,691,1,10718,88,69.0,8.0,I do not have enough information to answer. Pl...
1,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,3000000.0,...,2,0.0,4,0,1,5,1,1.0,4.8,NaN
2,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,NaN,...,12,6.0,108,226,0,4849,45,48.0,8.3,NaN
3,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,26435.0,...,23,18.0,203,12000,1,111841,413,260.0,8.3,NaN
4,Pandora's Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,9950.0,...,20,3.0,455,926,1,7431,84,71.0,8.0,NaN

In [ ]:
# read the movies data
# 1) Print number of rows and columns ---> df.shape
# 2) Show the data type of each columns ---> df.info()

In [38]:
df.groupby(['Country', 'Year'])[['IMDB Score', 'Duration', 'Gross Earnings']].mean()

                   IMDB Score    Duration  Gross Earnings
Country      Year
Aruba        1998    4.800000   91.000000    1.007614e+07
Australia    1979    7.000000   93.000000             NaN
             1981    7.600000   87.000000    9.003011e+06
             1982    7.300000  102.000000             NaN
             1985    6.200000  107.000000    3.620000e+07
...                       ...         ...             ...
USA          1998    6.418000  110.420000    4.676545e+07
             1999    6.326515  107.924242    4.263643e+07
West Germany 1967    6.000000   80.000000             NaN
             1981    8.400000  293.000000    1.143313e+07
             1984    7.400000   94.000000             NaN

[198 rows x 3 columns]

### Group by frequency counts
------------------------------

In [39]:
# Find the unique content rating for each country
df.groupby('Country')['Content Rating'].nunique()

Country
Aruba              1
Australia          4
Brazil             1
Canada             3
China              1
Czech Republic     1
Denmark            2
France             7
Germany            4
Hong Kong          2
India              1
Iran               1
Italy              7
Japan              5
Libya              1
Mexico             1
Netherlands        2
New Zealand        1
Norway             1
Peru               1
South Korea        1
Soviet Union       1
Spain              2
Sweden             1
Switzerland        1
UK                 9
USA               13
West Germany       3
Name: Content Rating, dtype: int64

In [40]:
df.groupby('Country')['Content Rating'].value_counts()

Country       Content Rating
Aruba         R                 1
Australia     R                 8
              PG-13             5
              PG                3
              G                 2
                               ..
USA           NC-17             3
              TV-G              1
West Germany  M                 1
              PG                1
              R                 1
Name: count, Length: 78, dtype: int64

In [45]:
df.head()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score,Unnamed: 25
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,22,9.0,481,691,1,10718,88,69.0,8.0,I do not have enough information to answer. Pl...
1,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,3000000.0,...,2,0.0,4,0,1,5,1,1.0,4.8,NaN
2,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,NaN,...,12,6.0,108,226,0,4849,45,48.0,8.3,NaN
3,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,26435.0,...,23,18.0,203,12000,1,111841,413,260.0,8.3,NaN
4,Pandora's Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,9950.0,...,20,3.0,455,926,1,7431,84,71.0,8.0,NaN

In [41]:
df.groupby('Year')['Language'].value_counts()

Year  Language
1927  German          1
1929  English         1
      German          1
1930  English         1
1932  English         1
                   ...
1998  Hindi           1
      Portuguese      1
1999  English       166
      German          1
      Japanese        1
Name: count, Length: 109, dtype: int64

### Aggregate Function

In [42]:
df['IMDB Score'].agg('min')

np.float64(2.3)

In [43]:
df['IMDB Score'].agg(['min', 'max', 'mean'])

min     2.300000
max     9.300000
mean    6.702167
Name: IMDB Score, dtype: float64

In [44]:
df.groupby('Country')['IMDB Score'].agg(['min', 'max', 'mean'])

                min  max      mean
Country
Aruba           4.8  4.8  4.800000
Australia       4.9  7.7  6.455556
Brazil          6.4  8.0  7.200000
Canada          2.8  7.9  6.336000
China           7.8  7.8  7.800000
Czech Republic  7.1  7.1  7.100000
Denmark         6.4  8.1  7.533333
France          4.6  8.0  6.761538
Germany         5.3  8.3  6.933333
Hong Kong       6.2  7.6  6.833333
India           7.8  7.8  7.800000
Iran            6.5  8.5  7.500000
Italy           6.1  8.9  7.418182
Japan           3.8  8.7  7.088889
Libya           8.4  8.4  8.400000
Mexico          6.8  6.8  6.800000
Netherlands     5.0  7.8  6.600000
New Zealand     7.4  7.6  7.500000
Norway          6.7  6.7  6.700000
Peru            5.4  5.4  5.400000
South Korea     2.7  2.7  2.700000
Soviet Union    8.1  8.1  8.100000
Spain           6.2  7.2  6.575000
Sweden          8.2  8.2  8.200000
Switzerland     5.8  5.8  5.800000
UK              3.0  8.5  6.873846
USA             2.3  9.3  6.672787
West Germany    6.0  8.4  7.266667

In [45]:
df.groupby('Country')['IMDB Score'].agg(['min', 'max', 'mean', 'count'])

                min  max      mean  count
Country
Aruba           4.8  4.8  4.800000      1
Australia       4.9  7.7  6.455556     18
Brazil          6.4  8.0  7.200000      2
Canada          2.8  7.9  6.336000     25
China           7.8  7.8  7.800000      1
Czech Republic  7.1  7.1  7.100000      1
Denmark         6.4  8.1  7.533333      3
France          4.6  8.0  6.761538     26
Germany         5.3  8.3  6.933333     12
Hong Kong       6.2  7.6  6.833333      3
India           7.8  7.8  7.800000      1
Iran            6.5  8.5  7.500000      2
Italy           6.1  8.9  7.418182     11
Japan           3.8  8.7  7.088889      9
Libya           8.4  8.4  8.400000      1
Mexico          6.8  6.8  6.800000      1
Netherlands     5.0  7.8  6.600000      3
New Zealand     7.4  7.6  7.500000      2
Norway          6.7  6.7  6.700000      1
Peru            5.4  5.4  5.400000      1
South Korea     2.7  2.7  2.700000      1
Soviet Union    8.1  8.1  8.100000      1
Spain           6.2  7.2  6.575000      4
Sweden          8.2  8.2  8.200000      1
Switzerland     5.8  5.8  5.800000      1
UK              3.0  8.5  6.873846    130
USA             2.3  9.3  6.672787   1073
West Germany    6.0  8.4  7.266667      3

### Creating and Manupulating the DataFrame

In [46]:
# Creating a series
# In pandas series are one dimensional data containers, similar to list

l = ['banana', 21]
s = pd.Series(l)
s

0    banana
1        21
dtype: object

In [47]:
# Example-2
data = ['Amit', 34, 'M']
index = ['Name', 'Age', 'Gender']

s = pd.Series(data, index=index)
s

Name      Amit
Age         34
Gender       M
dtype: object

In [49]:
s.loc['Name']

'Amit'

In [50]:
s.loc['Name']

'Amit'

In [52]:
s.iloc[0]

'Amit'

In [54]:
# Creating a DataFrame
students = {'Name': ['Amit', 'Anitha', 'Aswini', 'RK'],
            'Gender': ['M', 'F', 'F', 'M'],
            'Age': [34, 24, 23, 26]}

student_df = pd.DataFrame(students)
student_df

     Name Gender  Age
0    Amit      M   34
1  Anitha      F   24
2  Aswini      F   23
3      RK      M   26

In [55]:
student_df['Age'][1] = 27
student_df

/var/folders/rr/0n4wysh90tn8pghdwg390f580000gn/T/ipykernel_87341/957545061.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  student_df['Age'][1] = 27
/var/folders/rr/0n4wysh90tn8pghdwg390f580000gn/T/ipykernel_87341/957545061.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student_df['Age'][1] = 27

     Name Gender  Age
0    Amit      M   34
1  Anitha      F   27
2  Aswini      F   23
3      RK      M   26

In [56]:
student_df['Domain'] = ['NLP', 'CV', " ", 'ML']
student_df

     Name Gender  Age Domain
0    Amit      M   34    NLP
1  Anitha      F   27     CV
2  Aswini      F   23
3      RK      M   26     ML

In [59]:
# Merging
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }, index=[0, 1, 2, 3]
)

df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    }, index=[4, 5, 6, 7]
)

df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    }, index=[8, 9, 10, 11]
)

In [60]:
frames = [df1, df2, df3]
result = pd.concat(frames)
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [61]:
df4 = pd.DataFrame(
    {
        "B": ["B3", "B6", "B12", "B11"],
        "D": ["D8", "D9", "D10", "D11"],
        "F": ["F8", "F9", "F10", "F11"]
    }, index=[2, 3, 6, 7]
)

In [62]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [63]:
result = pd.concat([df1, df4])
result

     A    B    C    D    F
0   A0   B0   C0   D0  NaN
1   A1   B1   C1   D1  NaN
2   A2   B2   C2   D2  NaN
3   A3   B3   C3   D3  NaN
2  NaN   B3  NaN   D8   F8
3  NaN   B6  NaN   D9   F9
6  NaN  B12  NaN  D10  F10
7  NaN  B11  NaN  D11  F11

In [64]:
pd.concat([df1, df4], axis=1, join='inner')

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B3  D8  F8
3  A3  B3  C3  D3  B6  D9  F9

In [65]:
pd.concat([df1, df4], axis=0, join='inner')

     B    D
0   B0   D0
1   B1   D1
2   B2   D2
3   B3   D3
2   B3   D8
3   B6   D9
6  B12  D10
7  B11  D11

In [ ]:
#Q1) Using movies data, solve the following
'''
 Create a DataFrame containing only:
 Title
 Year
 Country
 Language
 IMDB Score
 Duration
'''

#Q2) For each country, find:
'''
- minimum IMDB Score
- Max IMDB score
- Average IMDB Score
- Number of movies
'''

#Q3) For each country, determine how many different content rating categories exist?

#Q4) For every country and year combination, calculate the minimum, max, and average IMDB Score